project:
  type: website

website:
  title: "OncoDerm AI"
  navbar:
    left:
      - href: docs/index.qmd
        text: Home
      - href: reference/index.qmd
        text: Reference

quartodoc:
  style: pkgdown
  dir: reference
  package: onco_derm_ai
  sections:
    - title: API Reference
      desc: The API reference for the OncoDerm AI package.
  

format:
  html:
    theme: cosmo
    css: docs/styles.css
    toc: true



