project:
  type: website

website:
  title: "OncoDerm AI"
  navbar:
    left:
      - href: docs/index.qmd
        text: Home
      - href: docs/cards/index.qmd
        text: Cards
      - href: reference/index.qmd
        text: Reference

quartodoc:
  style: pkgdown
  dir: reference
  package: onco_derm_ai
  title: API Reference
  sections:
    - title: data_preprocessing
      desc: Functions in the data_preprocessing pipeline
      contents:
        - normalizing_images
        - tensoring_resizing
  

format:
  html:
    theme: cosmo
    css: docs/styles.css
    toc: true



