project:
  type: website

website:
  title: "OncoDerm AI"
  navbar:
    left:
      - href: docs/index.qmd
        text: Home
      - href: docs/cards/index.qmd
        text: Cards
      - href: reference/index.qmd
        text: Reference

quartodoc:
  style: pkgdown
  dir: reference
  package: onco_derm_ai
  title: API Reference
  sections:
    - title: data_preprocessing
      desc: Functions in the data_preprocessing pipeline
      contents:
        - normalizing_images
        - tensoring_resizing
    - title: model_training
      desc: Functions in the model_training pipeline
      contents:
        - DermaMNISTDataset
        - preprocess_data_input
        - model_select
        - model_finetune
        - evaluate_model
        - log_model
    - title: ood_detection
      desc: Functions in the ood_detection pipeline
      contents:
        - prepare_data
        - train_wide_resnet
        - multi_mahalanobis_detector
    - title: conformal_prediction
      desc: Functions in the conformal_prediction pipeline
      contents:
        - data_prep
        - calibrate_predictor
        - evaluate_predictor

    - title: inference
      desc: Functions used in various inference pipelines
      contents:
        - resize_image
        - normalize_image
        - prepare_data_for_ood
        - ood_detection
        - predict
        - conformal_prediction
        - log_prediction
  

format:
  html:
    theme: cosmo
    css: docs/styles.css
    toc: true



