project:
  type: website

website:
  title: "OncoDerm AI"
  navbar:
    left:
      - href: docs/index.qmd
        text: Home
      - href: reference/index.qmd
        text: Reference

quartodoc:
  style: pkgdown
  dir: reference
  package: onco_derm_ai
  title: API Reference
  sections:
    - title: data_preprocessing
      desc: Functions in the data_preprocessing pipeline
      contents:
        - normalizing_images
        - tensoring_resizing
    - title: model_training
      desc: Functions in the model_training pipeline
      contents:
        - DermaMNISTDataset
        - preprocess_data_input
        - model_select
        - model_finetune
        - evaluate_model
        - log_model
    - title: ood_detection
      desc: Functions in the ood_detection pipeline
      contents:
        - prepare_data
        - rmd_detector
    - title: inference
      desc: Functions used in various inference pipelines
      contents:
        - resize_image
        - normalize_image
        - predict
  

format:
  html:
    theme: cosmo
    css: docs/styles.css
    toc: true



